HelloStavander2024 KeyCloak: properly enable health checks
Also remove deprecated proxy setting

diff --git a/ConfrenceMaterials/HelloStavander2024/docker-compose.yaml b/ConfrenceMaterials/HelloStavander2024/docker-compose.yaml
--- a/ConfrenceMaterials/HelloStavander2024/docker-compose.yaml
+++ b/ConfrenceMaterials/HelloStavander2024/docker-compose.yaml
@@ -838,7 +838,7 @@ services:
     environment:
       KC_BOOTSTRAP_ADMIN_USERNAME: "admin"
       KC_BOOTSTRAP_ADMIN_PASSWORD: "password"
-      KC_PROXY: "none"
+      KC_HEALTH_ENABLED: "true"
       KC_LOG_LEVEL: "INFO"
       KC_HTTP_PORT: "8088"
       KC_HTTP_HOST: 0.0.0.0
@@ -878,7 +878,7 @@ services:
             esac
             shift
           done
-          ehco "==> Creating demo user $${SUPPLIED_USER_NAME} in demo realm $${SUPPLIED_REALM}"
+          echo "==> Creating demo user $${SUPPLIED_USER_NAME} in demo realm $${SUPPLIED_REALM}"
           /opt/keycloak/bin/kcadm.sh create users \
             --target-realm $$SUPPLIED_REALM \
             --set username=$$SUPPLIED_USER_NAME \
@@ -897,7 +897,7 @@ services:
 
         while :
         do
-          exec 3<>/dev/tcp/127.0.0.1/8088
+          exec 3<>/dev/tcp/127.0.0.1/9000
           echo -e 'GET /health/ready HTTP/1.1\nhost: http://localhost/auth\nConnection: close\n\n' >&3
           if [ $? -eq 0 ]
           then
@@ -969,7 +969,7 @@ services:
         echo "To get user access token run curl --request POST --url http://localhost:8088/realms/demo-realm/protocol/openid-connect/token --header 'Content-Type: application/x-www-form-urlencoded' --data client_id=demo-client --data username=demo-admin --data password=password --data realm=demo-realm --data grant_type=password"
         sleep infinity
     healthcheck:
-      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/8088;echo -e 'GET /health/ready HTTP/1.1\nhost: http://localhost/auth\nConnection: close\n\n' >&3;if [ $? -eq 0 ]; then echo 'Healthcheck Successful';exit 0;else echo 'Healthcheck Failed';exit 1;fi;"]
+      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/9000;echo -e 'GET /health/ready HTTP/1.1\nhost: http://localhost/auth\nConnection: close\n\n' >&3;if [ $? -eq 0 ]; then echo 'Healthcheck Successful';exit 0;else echo 'Healthcheck Failed';exit 1;fi;"]
       start_period: "15s"
       interval: 30s
       timeout: 10s
